'use strict';

const assert = require('assert');
const { COMMENT_LABELS, classifyFacebookUrl, selectNewVerifiedReference, stableReference } = require('./facebook-page');
const { RecoveryBackoff, isBrowserClosedError, needsReviewError } = require('./recovery');

assert.equal(classifyFacebookUrl('https://www.facebook.com/'), 'CONNECTED');
assert.equal(classifyFacebookUrl('https://www.facebook.com/login/'), 'LOGIN_REQUIRED');
assert.equal(classifyFacebookUrl('https://www.facebook.com/checkpoint/123'), 'CHECKPOINT');
assert.equal(classifyFacebookUrl('https://example.com/'), 'INVALID');
assert(COMMENT_LABELS.some((pattern) => pattern.test('Write a comment')));
assert(COMMENT_LABELS.some((pattern) => pattern.test('เขียนความคิดเห็น')));
assert(stableReference('same') === stableReference('same'));
assert(stableReference('a') !== stableReference('b'));
assert(stableReference('a').startsWith('UNVERIFIED-'));
const oldComment = 'https://www.facebook.com/groups/1/posts/2/?comment_id=100';
const newComment = 'https://www.facebook.com/groups/1/posts/2/?comment_id=101';
const permalinkComment = 'https://www.facebook.com/groups/1/permalink/2/?comment_id=102';
const temporaryComment = 'https://www.facebook.com/example?comment_id=client%3Atemporary';
assert.equal(selectNewVerifiedReference([oldComment], [oldComment, newComment]), newComment);
assert.equal(selectNewVerifiedReference([oldComment], [permalinkComment]), permalinkComment);
assert.equal(selectNewVerifiedReference([oldComment], [oldComment]), '');
assert.equal(selectNewVerifiedReference([], [temporaryComment]), '');
const backoff = new RecoveryBackoff({ baseDelayMs: 100, maxDelayMs: 400 });
assert.equal(backoff.canAttempt(0), true);
assert.equal(backoff.failure(1000), 100);
assert.equal(backoff.canAttempt(1099), false);
assert.equal(backoff.canAttempt(1100), true);
assert.equal(backoff.failure(1100), 200);
assert.equal(backoff.failure(1300), 400);
assert.equal(backoff.failure(1700), 400);
backoff.success();
assert.equal(backoff.failures, 0);
assert.equal(backoff.canAttempt(0), true);
assert.equal(isBrowserClosedError(Error('browserContext.newPage: Target page, context or browser has been closed')), true);
assert.equal(needsReviewError(Error('Target closed')), 'BROWSER_CLOSED_NEEDS_REVIEW');
console.log('Facebook worker tests: 26/26 PASS');
